version: '3'

services:
  sqlcontainer:
    image: mysql:5.7
    restart: always
    env_file: ./proxyServerApp/.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service1
      MYSQL_USER: root_user
      MYSQL_PASSWORD: abc123
    ports:
      - 6033:3306
    volumes:
      - db-config-proxy:/etc/mysql
      - db-data-proxy:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  app:
    build:
      context: .
      dockerfile: ./proxyServerApp/Dockerfile
    image: timdanderson1/fecproxy1
    env_file: ./proxyServerApp/.env
    ports:
      - 3000:3000
    depends_on:
      - sqlcontainer
    stdin_open: true
    tty: true
    volumes:
      - ./mounted:/proxyServerApp

volumes:
  db-config-proxy:
  db-data-proxy: